// Auto-generated by scripts/build-icons.ts. Do not edit.
// Icon map for the docs site's default icon library (lucide),
// inlined from @iconify-json/lucide.
import type { ComponentProps } from "@solidjs/web";
import type { Component } from "solid-js";

const icon = (
  viewBox: string,
  body: string,
): Component<ComponentProps<"svg">> => {
  return (props) => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="1em"
      height="1em"
      viewBox={viewBox}
      innerHTML={body}
      {...props}
    />
  );
};

export const lucideIcons = {
  "arrow-up": icon(
    "0 0 24 24",
    `<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m5 12l7-7l7 7m-7 7V5"/>`,
  ),
  "check": icon(
    "0 0 24 24",
    `<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 6L9 17l-5-5"/>`,
  ),
  "chevron-down": icon(
    "0 0 24 24",
    `<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m6 9l6 6l6-6"/>`,
  ),
  "chevron-right": icon(
    "0 0 24 24",
    `<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m9 18l6-6l-6-6"/>`,
  ),
  "chevron-up": icon(
    "0 0 24 24",
    `<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m18 15l-6-6l-6 6"/>`,
  ),
  "circle-check": icon(
    "0 0 24 24",
    `<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="m9 12l2 2l4-4"/></g>`,
  ),
  "info": icon(
    "0 0 24 24",
    `<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4m0-4h.01"/></g>`,
  ),
  "panel-left": icon(
    "0 0 24 24",
    `<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><rect width="18" height="18" x="3" y="3" rx="2"/><path d="M9 3v18"/></g>`,
  ),
  "x": icon(
    "0 0 24 24",
    `<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 6L6 18M6 6l12 12"/>`,
  ),
};

export type LucideIconName = keyof typeof lucideIcons;
