/**
 * Builds all registry outputs:
 *
 * - `src/__registry__/index.tsx` — lazy component index for the docs site.
 * - `public/r/<name>.json` — registry items in the official shadcn v4
 *   registry-item format, in the default style, icons resolved to the
 *   default library.
 * - `public/r/icons/<library>/<name>.json` — per-icon-library variants of
 *   every item, in the default style.
 * - `public/r/styles/<style>/icons/<library>/<name>.json` — the full
 *   style x icon-library fan-out. The default style is written to the
 *   unprefixed paths above as well, so registries pinned before styles
 *   existed keep resolving.
 * - `public/r/themes/<name>.json` — theme items (cssVars only).
 * - `public/r/registry.json` + `public/r/index.json` — item index.
 * - `public/registry/**` — legacy format predating shadcn-solidjs, icons
 *   resolved to the default library.
 *
 * Authored components carry two kinds of build-time markers, neither of
 * which ships to consumers:
 *
 * - `cn-*` style markers, inlined per style from
 *   `src/registry/styles/style-<style>.css` (see
 *   src/lib/registry/style-map.ts). The docs site instead styles the
 *   markers at runtime by importing those files in app.css.
 * - IconPlaceholder components, resolved into concrete
 *   `~icons/<library>/<name>` imports (unplugin-icons / @iconify-json on
 *   the consumer side).
 *
 * Run with: deno run -A ./src/scripts/build-registry.ts
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path, { basename } from "node:path";
import process from "node:process";

import { resolveIcons } from "../lib/registry/resolve-icons.ts";
import { createStyleMap, inlineStyles } from "../lib/registry/style-map.ts";
import {
  defaultIconLibrary,
  iconLibraries,
  iconLibraryNames,
} from "../registry/icons/icon-libraries.ts";
import { registry } from "../registry/index.ts";
import { type RegistryItem, registrySchema } from "../registry/schema.ts";
import {
  defaultStyle,
  type StyleName,
  styleNames,
} from "../registry/styles.ts";

const LEGACY_PATH = path.join(process.cwd(), "public/registry");
const R_PATH = path.join(process.cwd(), "public/r");
const HOMEPAGE = "https://shadcn-solidjs.com";

const result = registrySchema.safeParse(registry);
if (!result.success) {
  console.error(result.error.issues);
  process.exit(1);
}
const items = result.data;

// #######################################
//    Style + icon resolution
// #######################################

const styleMaps = new Map(
  styleNames.map((style) => [
    style,
    createStyleMap(
      readFileSync(
        path.join(
          process.cwd(),
          "src",
          "registry",
          "styles",
          `style-${style}.css`,
        ),
        "utf8",
      ),
    ),
  ]),
);

/** Authored sources, read once and reused across every style. */
const sourceCache = new Map<string, string>();

function readSource(filePath: string) {
  const cached = sourceCache.get(filePath);
  if (cached !== undefined) {
    return cached;
  }
  const content = readFileSync(
    path.join(process.cwd(), "src", "registry", filePath),
    "utf8",
  ).replaceAll("\r\n", "\n");
  sourceCache.set(filePath, content);
  return content;
}

/**
 * Reads an item's authored files with the given style's `cn-*` markers
 * already inlined; only IconPlaceholder resolution remains per icon
 * library.
 */
function readItemFiles(item: RegistryItem, style: StyleName) {
  const styleMap = styleMaps.get(style)!;
  return item.files.map((file) => ({
    ...file,
    content: inlineStyles(readSource(file.path), styleMap),
  }));
}

// #######################################
//    BUILD __registry__/index.tsx
// #######################################

let index = `
// @ts-nocheck: autogenerated registry index
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import type { RegistryIndex } from "~/registry/schema.ts"

import { lazy } from "solid-js"

export const Index: RegistryIndex = {
`;
for (const item of items) {
  // Themes carry no files; lib and hook items are plain modules rather than
  // components the docs site can lazily render.
  if (item.type === "theme" || item.type === "lib" || item.type === "hook") {
    continue;
  }
  const componentPath = item.files[0]?.path ??
    `${item.type}/${item.name}.tsx`;
  index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    component: lazy(() => import("~/registry/${componentPath}")),
    files: [${
    item.files.map(
      (file) =>
        `{
      path: "registry/${file.path}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`,
    )
  }],
  },`;
}
index += `
}
`;

writeFileSync(
  path.join(process.cwd(), "src", "__registry__", "index.tsx"),
  index,
);

// #######################################
//    BUILD public/r (shadcn v4 format)
// #######################################

function toRegistryItem(
  item: RegistryItem,
  files: { path: string; content: string; type: string; target?: string }[],
  devDependencies: string[],
) {
  return {
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    name: item.name,
    type: `registry:${item.type}`,
    ...(item.title ? { title: item.title } : {}),
    ...(item.description ? { description: item.description } : {}),
    ...(item.dependencies?.length ? { dependencies: item.dependencies } : {}),
    ...(devDependencies.length ? { devDependencies } : {}),
    ...(item.registryDependencies?.length
      ? { registryDependencies: item.registryDependencies }
      : {}),
    ...(files.length
      ? {
        files: files.map((file) => ({
          path: `src/registry/${file.path}`,
          content: file.content,
          type: `registry:${file.type}`,
          ...(file.target ? { target: file.target } : {}),
        })),
      }
      : {}),
    ...(item.cssVars ? { cssVars: item.cssVars } : {}),
  };
}

function writeJson(filePath: string, payload: unknown) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  // Trailing newline so the emitted registry is already `deno fmt` clean.
  // Without it every build leaves ~2900 files that fmt wants to touch and the
  // next build reverts, which the pre-commit hook turns into churn.
  writeFileSync(filePath, `${JSON.stringify(payload, null, 2)}\n`, "utf8");
}

const indexItems: Record<string, unknown>[] = [];

for (const item of items) {
  if (item.type === "theme") {
    // Themes carry cssVars rather than files, so nothing in them varies
    // by style or icon library.
    const payload = toRegistryItem(item, [], []);
    writeJson(path.join(R_PATH, "themes", `${item.name}.json`), payload);
    indexItems.push({ ...payload, files: undefined });
    continue;
  }

  // lib and hook items carry no icons, so the fan-out below writes five
  // identical variants. That is deliberate: it keeps every item addressable
  // under the same `icons/<library>/` prefix the CLI selects per icon
  // library, so resolving a ui item's registryDependencies never has to fall
  // back to a different path. The style fan-out works the same way.
  if (item.type !== "ui" && item.type !== "lib" && item.type !== "hook") {
    continue;
  }

  for (const style of styleNames) {
    const files = readItemFiles(item, style);

    for (const library of iconLibraryNames) {
      let usesIcons = false;
      const resolved = files.map((file) => {
        const { code, icons } = resolveIcons(file.content, library);
        if (icons.length > 0) {
          usesIcons = true;
        }
        return { ...file, content: code };
      });
      const devDependencies = usesIcons
        ? ["unplugin-icons", iconLibraries[library].package]
        : [];
      const payload = toRegistryItem(item, resolved, devDependencies);

      writeJson(
        path.join(
          R_PATH,
          "styles",
          style,
          "icons",
          library,
          `${item.name}.json`,
        ),
        payload,
      );

      // The default style also lives at the unprefixed paths, so
      // registries pinned before styles existed keep resolving.
      if (style === defaultStyle) {
        writeJson(
          path.join(R_PATH, "icons", library, `${item.name}.json`),
          payload,
        );
        if (library === defaultIconLibrary) {
          writeJson(path.join(R_PATH, `${item.name}.json`), payload);
          indexItems.push({ ...payload, files: undefined });
        }
      }
    }
  }
}

const registryIndex = {
  $schema: "https://ui.shadcn.com/schema/registry.json",
  name: "shadcn-solidjs",
  homepage: HOMEPAGE,
  items: indexItems,
};
writeJson(path.join(R_PATH, "registry.json"), registryIndex);
writeJson(path.join(R_PATH, "index.json"), registryIndex);

// #######################################
//    BUILD public/registry (legacy pre-shadcn-solidjs format)
// #######################################

for (const item of items) {
  if (item.type !== "ui") {
    continue;
  }

  // The legacy format predates styles, so it ships the default one.
  let usesIcons = false;
  const files = readItemFiles(item, defaultStyle).map((file) => {
    const { code, icons } = resolveIcons(file.content, defaultIconLibrary);
    if (icons.length > 0) {
      usesIcons = true;
    }
    return { name: basename(file.path), content: code };
  });

  const payload = {
    ...item,
    dependencies: usesIcons
      ? [
        ...(item.dependencies ?? []),
        "unplugin-icons",
        iconLibraries[defaultIconLibrary].package,
      ]
      : item.dependencies,
    files,
  };

  writeJson(path.join(LEGACY_PATH, item.type, `${item.name}.json`), payload);
}

const legacyIndex = items
  .filter((item) => item.type === "ui")
  .map((item) => ({
    ...item,
    files: item.files.map((file) => file.path),
  }));
writeJson(path.join(LEGACY_PATH, "index.json"), legacyIndex);

console.log(
  `Styles: ${styleNames.join(", ")} (default ${defaultStyle}).`,
);
console.log(
  `Built ${items.filter((i) => i.type === "ui").length} ui items, ` +
    `${items.filter((i) => i.type === "lib").length} lib items, ` +
    `${items.filter((i) => i.type === "hook").length} hooks ` +
    `(x${styleNames.length} styles x${iconLibraryNames.length} icon libraries), ` +
    `${items.filter((i) => i.type === "theme").length} themes.`,
);
