/**
 * Builds all registry outputs:
 *
 * - `src/__registry__/index.tsx` — lazy component index for the docs site.
 * - `public/r/<name>.json` — registry items in the official shadcn v4
 *   registry-item format, icons resolved to the default library.
 * - `public/r/icons/<library>/<name>.json` — per-icon-library variants of
 *   every ui item that uses icons.
 * - `public/r/themes/<name>.json` — theme items (cssVars only).
 * - `public/r/registry.json` + `public/r/index.json` — item index.
 * - `public/registry/**` — legacy format consumed by solidui-cli, icons
 *   resolved to the default library.
 *
 * Authored components carry two kinds of build-time markers, neither of
 * which ships to consumers:
 *
 * - `cn-*` style markers, inlined from `src/registry/styles/style-nova.css`
 *   (see src/lib/registry/style-map.ts). The docs site instead styles the
 *   markers at runtime by importing that CSS in app.css.
 * - IconPlaceholder components, resolved into concrete
 *   `~icons/<library>/<name>` imports (unplugin-icons / @iconify-json on
 *   the consumer side).
 *
 * Run with: deno run -A ./src/scripts/build-registry.ts
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path, { basename } from "node:path";
import process from "node:process";

import { safeParse } from "valibot";

import { resolveIcons } from "../lib/registry/resolve-icons.ts";
import { createStyleMap, inlineStyles } from "../lib/registry/style-map.ts";
import {
  defaultIconLibrary,
  iconLibraries,
  iconLibraryNames,
} from "../registry/icons/icon-libraries.ts";
import { registry } from "../registry/index.ts";
import { type RegistryItem, registrySchema } from "../registry/schema.ts";

const LEGACY_PATH = path.join(process.cwd(), "public/registry");
const R_PATH = path.join(process.cwd(), "public/r");
const HOMEPAGE = "https://shadcn-solid.com";

const result = safeParse(registrySchema, registry);
if (!result.success) {
  console.error(result.issues);
  process.exit(1);
}
const items = result.output;

// #######################################
//    Style + icon resolution
// #######################################

const styleMap = createStyleMap(
  readFileSync(
    path.join(process.cwd(), "src", "registry", "styles", "style-nova.css"),
    "utf8",
  ),
);

/**
 * Reads an item's authored files with `cn-*` style markers already
 * inlined; only IconPlaceholder resolution remains per icon library.
 */
function readItemFiles(item: RegistryItem) {
  return item.files.map((file) => ({
    ...file,
    content: inlineStyles(
      readFileSync(
        path.join(process.cwd(), "src", "registry", file.path),
        "utf8",
      ).replaceAll("\r\n", "\n"),
      styleMap,
    ),
  }));
}

// #######################################
//    BUILD __registry__/index.tsx
// #######################################

let index = `
// @ts-nocheck: autogenerated registry index
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import { lazy } from "solid-js"

import type { RegistryIndex } from "~/registry/schema.ts"

export const Index: RegistryIndex = {
`;
for (const item of items) {
  if (item.type === "theme") {
    continue;
  }
  const componentPath = item.files[0]?.path ??
    `${item.type}/${item.name}.tsx`;
  index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    component: lazy(() => import("~/registry/${componentPath}")),
    files: [${
    item.files.map(
      (file) =>
        `{
      path: "registry/${file.path}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`,
    )
  }],
  },`;
}
index += `
}
`;

writeFileSync(
  path.join(process.cwd(), "src", "__registry__", "index.tsx"),
  index,
);

// #######################################
//    BUILD public/r (shadcn v4 format)
// #######################################

function toRegistryItem(
  item: RegistryItem,
  files: { path: string; content: string; type: string; target?: string }[],
  devDependencies: string[],
) {
  return {
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    name: item.name,
    type: `registry:${item.type}`,
    ...(item.title ? { title: item.title } : {}),
    ...(item.description ? { description: item.description } : {}),
    ...(item.dependencies?.length ? { dependencies: item.dependencies } : {}),
    ...(devDependencies.length ? { devDependencies } : {}),
    ...(item.registryDependencies?.length
      ? { registryDependencies: item.registryDependencies }
      : {}),
    ...(files.length
      ? {
        files: files.map((file) => ({
          path: `src/registry/${file.path}`,
          content: file.content,
          type: `registry:${file.type}`,
          ...(file.target ? { target: file.target } : {}),
        })),
      }
      : {}),
    ...(item.cssVars ? { cssVars: item.cssVars } : {}),
  };
}

function writeJson(filePath: string, payload: unknown) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, JSON.stringify(payload, null, 2), "utf8");
}

const indexItems: Record<string, unknown>[] = [];

for (const item of items) {
  if (item.type === "theme") {
    const payload = toRegistryItem(item, [], []);
    writeJson(path.join(R_PATH, "themes", `${item.name}.json`), payload);
    indexItems.push({ ...payload, files: undefined });
    continue;
  }

  if (item.type !== "ui") {
    continue;
  }

  const files = readItemFiles(item);

  for (const library of iconLibraryNames) {
    let usesIcons = false;
    const resolved = files.map((file) => {
      const { code, icons } = resolveIcons(file.content, library);
      if (icons.length > 0) {
        usesIcons = true;
      }
      return { ...file, content: code };
    });
    const devDependencies = usesIcons
      ? ["unplugin-icons", iconLibraries[library].package]
      : [];
    const payload = toRegistryItem(item, resolved, devDependencies);
    writeJson(
      path.join(R_PATH, "icons", library, `${item.name}.json`),
      payload,
    );
    if (library === defaultIconLibrary) {
      writeJson(path.join(R_PATH, `${item.name}.json`), payload);
      indexItems.push({ ...payload, files: undefined });
    }
  }
}

const registryIndex = {
  $schema: "https://ui.shadcn.com/schema/registry.json",
  name: "shadcn-solid",
  homepage: HOMEPAGE,
  items: indexItems,
};
writeJson(path.join(R_PATH, "registry.json"), registryIndex);
writeJson(path.join(R_PATH, "index.json"), registryIndex);

// #######################################
//    BUILD public/registry (legacy, solidui-cli)
// #######################################

for (const item of items) {
  if (item.type !== "ui") {
    continue;
  }

  let usesIcons = false;
  const files = readItemFiles(item).map((file) => {
    const { code, icons } = resolveIcons(file.content, defaultIconLibrary);
    if (icons.length > 0) {
      usesIcons = true;
    }
    return { name: basename(file.path), content: code };
  });

  const payload = {
    ...item,
    dependencies: usesIcons
      ? [
        ...(item.dependencies ?? []),
        "unplugin-icons",
        iconLibraries[defaultIconLibrary].package,
      ]
      : item.dependencies,
    files,
  };

  writeJson(path.join(LEGACY_PATH, item.type, `${item.name}.json`), payload);
}

const legacyIndex = items
  .filter((item) => item.type === "ui")
  .map((item) => ({
    ...item,
    files: item.files.map((file) => file.path),
  }));
writeJson(path.join(LEGACY_PATH, "index.json"), legacyIndex);

console.log(
  `Built ${items.filter((i) => i.type === "ui").length} ui items ` +
    `(x${iconLibraryNames.length} icon libraries), ` +
    `${items.filter((i) => i.type === "theme").length} themes.`,
);
