/**
 * Generates the icon map used by `IconPlaceholder` to render the docs site
 * with the default icon library, and validates every icon name declared on
 * `IconPlaceholder` markers against the @iconify-json data of all supported
 * libraries.
 *
 * The docs map inlines SVG bodies from the iconify data so the app never
 * imports `~icons/*` virtual modules (which `deno check` cannot resolve);
 * those imports appear only in the built registry JSON, where consumers
 * resolve them with unplugin-icons.
 *
 * Run with: deno run -A ./src/scripts/build-icons.ts
 */
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import process from "node:process";

import {
  defaultIconLibrary,
  iconLibraries,
  type IconLibrary,
  iconLibraryNames,
} from "../registry/icons/icon-libraries.ts";

const REGISTRY_PATH = path.join(process.cwd(), "src", "registry");
const ICONS_PATH = path.join(REGISTRY_PATH, "icons");

interface IconifyData {
  icons: Record<string, { body: string; width?: number; height?: number }>;
  aliases?: Record<string, { parent: string }>;
  width?: number;
  height?: number;
}

function findIconifyData(library: IconLibrary): IconifyData {
  let dir = process.cwd();
  while (true) {
    const candidate = path.join(
      dir,
      "node_modules",
      iconLibraries[library].package,
      "icons.json",
    );
    if (existsSync(candidate)) {
      return JSON.parse(readFileSync(candidate, "utf8"));
    }
    const parent = path.dirname(dir);
    if (parent === dir) {
      throw new Error(
        `Cannot find ${
          iconLibraries[library].package
        }/icons.json — is it installed?`,
      );
    }
    dir = parent;
  }
}

function resolveIcon(data: IconifyData, name: string) {
  const resolved = data.aliases?.[name]
    ? data.icons[data.aliases[name].parent]
    : data.icons[name];
  if (!resolved) return undefined;
  return {
    body: resolved.body,
    width: resolved.width ?? data.width ?? 16,
    height: resolved.height ?? data.height ?? 16,
  };
}

function* walk(dir: string): Generator<string> {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name.startsWith("__")) continue;
      yield* walk(full);
    } else if (entry.name.endsWith(".tsx")) {
      yield full;
    }
  }
}

function pascalCase(iconName: string): string {
  return iconName
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

// Collect icon names per library from IconPlaceholder attributes.
const used = new Map<IconLibrary, Set<string>>(
  iconLibraryNames.map((name) => [name, new Set<string>()]),
);

for (const file of walk(REGISTRY_PATH)) {
  const source = readFileSync(file, "utf8");
  for (const library of iconLibraryNames) {
    const attr = new RegExp(`\\b${library}="([^"]+)"`, "g");
    for (const match of source.matchAll(attr)) {
      used.get(library)!.add(match[1]);
    }
  }
}

// Validate every declared name against the iconify data.
const data = new Map<IconLibrary, IconifyData>(
  iconLibraryNames.map((name) => [name, findIconifyData(name)]),
);
let invalid = 0;
for (const library of iconLibraryNames) {
  for (const name of used.get(library)!) {
    if (!resolveIcon(data.get(library)!, name)) {
      console.error(`Unknown ${library} icon: "${name}"`);
      invalid++;
    }
  }
}
if (invalid > 0) {
  process.exit(1);
}

// Generate the default-library map consumed by IconPlaceholder.
const names = [...used.get(defaultIconLibrary)!].sort();
const defaultData = data.get(defaultIconLibrary)!;

let output = `// Auto-generated by scripts/build-icons.ts. Do not edit.
// Icon map for the docs site's default icon library (${defaultIconLibrary}),
// inlined from ${iconLibraries[defaultIconLibrary].package}.
import type { Component, ComponentProps } from "solid-js";

const icon = (
  viewBox: string,
  body: string,
): Component<ComponentProps<"svg">> => {
  return (props) => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="1em"
      height="1em"
      viewBox={viewBox}
      innerHTML={body}
      {...props}
    />
  );
};

export const ${defaultIconLibrary}Icons = {
`;
for (const name of names) {
  const resolved = resolveIcon(defaultData, name)!;
  const body = resolved.body.replaceAll("\\", "\\\\").replaceAll("`", "\\`")
    .replaceAll("${", "\\${");
  output +=
    `  "${name}": icon("0 0 ${resolved.width} ${resolved.height}", \`${body}\`),\n`;
}
output += `};

export type ${
  pascalCase(defaultIconLibrary)
}IconName = keyof typeof ${defaultIconLibrary}Icons;
`;

const outDir = path.join(ICONS_PATH, `__${defaultIconLibrary}__`);
mkdirSync(outDir, { recursive: true });
writeFileSync(path.join(outDir, "index.tsx"), output);

console.log(
  `Generated __${defaultIconLibrary}__/index.tsx with ${names.length} icons.`,
);
for (const library of iconLibraryNames) {
  console.log(`  ${library}: ${used.get(library)!.size} icon names validated`);
}
