/**
 * Generates the docs-only design tokens that vary by style.
 *
 * The docs shell frames things the registry does not: the component
 * preview, the install command block, the code collapsible. They should
 * sit at the same radius as the surfaces they wrap, which differs
 * sharply per style -- `rounded-none` in sera and lyra, `rounded-4xl` in
 * luma -- so hardcoding one value leaves a rounded frame around square
 * content in half the styles.
 *
 * shadcn-svelte solves this by enumerating a class per style at each
 * call site (`style-nova:h-7 style-sera:h-9 ...`). We have several
 * surfaces wanting the same value, and each style already declares it on
 * `cn-card`, so this reads it from there and emits one custom property
 * per style. Docs code then says `rounded-(--docs-surface-radius)` once.
 *
 * Output is committed so `deno task dev` works without a build step.
 *
 * Run with: deno run -A ./src/scripts/build-docs-tokens.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";

import { createStyleMap } from "../lib/registry/style-map.ts";
import { styleNames } from "../registry/styles.ts";

const STYLES_DIR = path.join(process.cwd(), "src", "registry", "styles");
const OUT = path.join(process.cwd(), "src", "styles", "style-docs.css");

/** The surface whose radius the docs frames should match. */
const SOURCE_MARKER = "cn-card";

/**
 * Turns a Tailwind radius utility into the CSS value it resolves to, so
 * the token can be consumed with `rounded-(--docs-surface-radius)`.
 */
function radiusValue(token: string): string {
  if (token === "rounded-none") return "0";
  if (token === "rounded-full") return "calc(infinity * 1px)";
  if (token === "rounded") return "var(--radius)";

  const arbitrary = token.match(/^rounded-\[(.+)\]$/);
  if (arbitrary) {
    // Tailwind encodes spaces as underscores inside arbitrary values.
    return arbitrary[1].replaceAll("_", " ");
  }

  const named = token.match(/^rounded-([a-z0-9]+)$/);
  if (named) return `var(--radius-${named[1]})`;

  throw new Error(`Cannot resolve radius utility "${token}"`);
}

const rules: string[] = [];

for (const style of styleNames) {
  const map = createStyleMap(
    readFileSync(path.join(STYLES_DIR, `style-${style}.css`), "utf8"),
  );
  const tokens = (map[SOURCE_MARKER] ?? "").split(/\s+/).filter(Boolean);
  // A style that declares no radius leaves the surface square, which is
  // a deliberate choice in sera rather than an omission.
  const radius = tokens.find((token) => /^rounded(-|$)/.test(token));
  const value = radius ? radiusValue(radius) : "0";
  rules.push(
    `  .style-${style} {\n    --docs-surface-radius: ${value};\n  }`,
  );
  console.log(
    `${style.padEnd(5)} ${(radius ?? "(none)").padEnd(14)} -> ${value}`,
  );
}

const css = `/*
 * Docs-only tokens that vary by style. Generated by
 * ./src/scripts/build-docs-tokens.ts from each style's \`.${SOURCE_MARKER}\`
 * radius -- do not edit by hand.
 *
 * Consumed as \`rounded-(--docs-surface-radius)\` by the docs shell so its
 * frames match the surfaces they wrap in every style.
 */
@layer components {
${rules.join("\n\n")}
}
`;

writeFileSync(OUT, css);
console.log(`\nWrote ${path.relative(process.cwd(), OUT)}`);
